# Q.1 Write Python programs to use various operators in Python.

In [17]:
# Arithematic Operators.

a=int(input("Enter first number,a="))
b=int(input("Enter second number,b="))
add=a+b
sub=a-b
multi=a*b
div=a/b
print("a+b=",add)
print("a-b=",sub)
print("a*b=",multi)
print("a/b=",div)

Enter first number,a=3
Enter second number,b=33
a+b= 36
a-b= -30
a*b= 99
a/b= 0.09090909090909091


In [58]:
# Comparision operators and is ,is not.

a=int(input("Enter 1st  number a="))
b=int(input("Enter 2nd number  b="))
c=int(input("Enter 3rd number  c="))
d=c
print("a",a<b)
print("b>=c",b>=c)
print("d==c",d==c)
print("a!=b",a!=b)
print("d==c is not a!=b",d==c is not a!=b)
print("b==c is d==c",b==c is d==c) 

Enter 1st  number a=34 
Enter 2nd number  b=2
Enter 3rd number  c=33
a False
b>=c False
d==c True
a!=b True
d==c is not a!=b True
b==c is d==c False


In [59]:
# Assignment operators.

a=int(input("Enter 1st  number a="))
b=int(input("Enter 2nd number  b="))
c=int(input("Enter 3rd number  c="))
print("a+=5 is",a+5)
print("b-=5 is",a-5)
print("c/5= is",c/5)
print("a= ",a)
print("a=a|5 is",a|5)
print("b=",b)
print("b|=5 is",b|5)
print("c=",c)
print("c^2 is",c^2)
print("a=",a)
print("a>>=5 is",a>>5)
print("a=",a)
print("a<<=5 is",a<<5)

Enter 1st  number a=3
Enter 2nd number  b=22
Enter 3rd number  c=3
a+=5 is 8
b-=5 is -2
c/5= is 0.6
a=  3
a=a|5 is 7
b= 22
b|=5 is 23
c= 3
c^2 is 1
a= 3
a>>=5 is 0
a= 3
a<<=5 is 96


In [60]:
# Examples of Identity operators.

a1=4
b1=4
a2='PrayagVK'
b2='PrayagV_15'
a3=[3,4,2]
b3=[2,3,7]

print(a1 is not a2)

print(a2==b2)

print(a3==b3)

True
False
False


In [30]:
# Examples of Membership operator.

x='Hello this is my world'
y={1:'a',2:'b'}

print('h' in x)

print('Hello ' not in x)

print('3 is not dictionary key' not in y.keys())

print('c is a dictionary value' in y.items())

True
False
True
False


# Q.2 Create list of elements and slice and dice it

In [1]:
# List where entries are string.
## length of list

a=['d','g','h','k','r','u','i','r','o','d','p','j']
len(a)

12

In [2]:
# Selecting entries from list.

a[1:5]

['g', 'h', 'k', 'r']

In [3]:
# Reversing the list.

a[::-1]

['j', 'p', 'd', 'o', 'r', 'i', 'u', 'r', 'k', 'h', 'g', 'd']

In [4]:
# Selecting entries from list using reverse indexing.

a[-4:-1] 

['o', 'd', 'p']

In [5]:
# Selecting entries from the beginning upto some index.

a[:3]

['d', 'g', 'h']

In [6]:
# Selecting entries from a particular index.

a[3:]

['k', 'r', 'u', 'i', 'r', 'o', 'd', 'p', 'j']

In [7]:
# Selecting entries from the list using step size of 3

a[::3]

['d', 'k', 'i', 'd']

In [8]:
# Entries of list are integers.
# Length of list.

b=[11,12,13,14,15,23,34,36,67,56,44,39]
len(b)

12

In [9]:
# Selecting entries from list.

b[3:7]

[14, 15, 23, 34]

In [10]:
# Reversing the list.

b[::-1]

[39, 44, 56, 67, 36, 34, 23, 15, 14, 13, 12, 11]

In [11]:
# Selecting entries from list using reverse indexing.

b[-5:-2]

[36, 67, 56]

In [12]:
# Selecting entries from the beginning upto some index.

b[:6]

[11, 12, 13, 14, 15, 23]

In [13]:
# Selecting entries from a particular index.

b[3:]

[14, 15, 23, 34, 36, 67, 56, 44, 39]

In [14]:
# Selecting entries from the list using step size of 4

b[::4]

[11, 15, 67]

# Q.3 Using while loop accept numbers until sum of numbers is less than 100.

In [66]:
a=1
s=0
x=0
while a!=0:
    print("Current sum is",s)
    a=float(input("Enter a number "))
    s=s+a
    if (s>=100):
        print(s,"The sum is greater than or equal to 100")
        break
    else:
        print("Total sum is",s)

Current sum is 0
Enter a number 8
Total sum is 8.0
Current sum is 8.0
Enter a number 33
Total sum is 41.0
Current sum is 41.0
Enter a number 3
Total sum is 44.0
Current sum is 44.0
Enter a number 43
Total sum is 87.0
Current sum is 87.0
Enter a number 3
Total sum is 90.0
Current sum is 90.0
Enter a number 32
122.0 The sum is greater than or equal to 100


# Q.4 Write a Python program to Read and write Excel files.

In [56]:
import xlsxwriter

workbook=xlsxwriter.Workbook("My Workbook.xlsx")

worksheet=workbook.add_worksheet("Sheet 1")

scores=(['Name','Marks'],['Dileep',100],['Kiran',93],['Rohit',101],['Darshan',99],['Sangu',87],['Mallu',78])

# Start from first cell. Row and column are indexed zero.
row=0
col=0
for name, score in (scores):
    worksheet.write(row,col,name)
    worksheet.write(row,col+1,score)
    row+=1
    
workbook.close()

In [57]:
import pandas as pd
df=pd.read_excel("My Workbook.xlsx")
df.sample(2)

Name  Marks
2  Rohit    101
4  Sangu     87

# Q.5 Create a 3 x 3 matrix with values ranging from 2 to 10 using numpy.

In [15]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Q.6 Write a Python program to convert a list of numeric values one-dimensional NumPy array.

In [34]:
a=[1,2,4,44,3,22]
print(type(a))
b=np.asarray(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


# Q.7 Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [32]:
N=np.zeros(10)
print(N)

# Updating sixth value to 11

N[6]=11

print(N)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
